### ISSUE TITLE
Update GitHub Actions workflow to read Python version requirement from `pyproject.toml`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-orcid-creditor#24]
Current approach has the version hard-coded:

https://github.com/microbiomedata/nmdc-orcid-creditor/blob/09e1ec83220d41d40d88d6cd544b4bcaac36ed84/.github/workflows/build-and-push-image.yaml#L23-L28

Proposal:

```yaml
    - name: Set up Python  # docs: https://github.com/actions/setup-python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"  # gets the version requirement from `pyproject.toml`
```
